config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :impact_cards do
    resources :initiatives, only: [:show], controller: 'impact_cards/initiatives'
  end

  namespace :initiatives do
    resources :imports, only: %i[new create update]
  end

  namespace :labels do
    resources :communities
    resources :stakeholder_types
    resources :subsystem_tags
    resources :wicked_problems
  end

  resources :checklist_items, only: %i[show edit update]

  namespace :organisations do
    resources :imports, only: %i[new create update]
  end

  namespace :transition_card_comments do
    resources :imports, only: %i[new create update], controller: '/scorecard_comments/imports'
  end

  # TODO: Fix this route once we have a proper transition_card_comments import
  namespace :sustainable_development_goal_alignment_card_comments do
    resources :imports, only: %i[new create update], controller: '/scorecard_comments/imports'
  end

  devise_for :users, controllers: {
    invitations: 'invitations'
   }

  resources :accounts do
    member do
      get 'switch'
    end
  end

  resources :characteristics do
    member do
      get 'description'
    end
  end

  resources :focus_area_groups
  resources :focus_areas
  resources :initiatives do
    resources :checklist_items do
      member do
        post 'update_comment'
        post 'create_comment'
        get 'comment_status'
      end
    end
    get 'linked'
  end
  resources :initiatives_organisations
  resources :initiatives_subsystem_tags
  resources :organisations

  resources :transition_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end
  end

  resources :sustainable_development_goal_alignment_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'targets_network_map'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end

    resources :characteristics,
              only: [:show],
              controller: 'sustainable_development_goal_alignment_cards',
              action: 'characteristic'
  end

  resources :ecosystem_maps do
    resources :organisations, only: [:show], controller: 'ecosystem_maps/organisations'
  end

  resources :shared,
            constraints: {
              id: /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(\d+)/
            },
            only: [:show] do
    member do
      get 'targets_network_map'
    end

    resources :characteristics, only: [:show], controller: 'shared', action: 'characteristic'
  end

  resources :users do
    post :stop_impersonating, on: :collection

    post :impersonate, on: :member

    member do
      get 'undelete'
      get 'resend_invitation'
      get 'remove_from_account'
    end
  end

  resources :reports, only: [:index] do
    collection do
      post 'initiatives'
      post 'stakeholders'
      get 'scorecard_activity'
      post 'scorecard_activity'
      post 'transition_card_stakeholders'
      post 'scorecard_comments'
      get 'scorecard_comments'
      get 'transition_card_activity'
      post 'transition_card_activity'
      get 'subsystem_summary'
      post 'subsystem_summary'
      get 'cross_account_percent_actual'
      post 'cross_account_percent_actual'
      get 'cross_account_percent_actual_by_focus_area'
      post 'cross_account_percent_actual_by_focus_area'
      get 'cross_account_percent_actual_by_focus_area_tabbed'
      post 'cross_account_percent_actual_by_focus_area_tabbed'
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'reports', to: 'reports#index'
  get 'activities', to: 'activities#index'
  get 'contributors', to: 'home#contributors'

  namespace :system do
    resources :stakeholder_types
  end

  root to: 'home#index'
end

app/models/initiatives.rb
# frozen_string_literal: true

# Initiatives module, namepsace for all organisation related models and services
module Initiatives
  def self.table_name_prefix
    'initiatives_'
  end
end

app/controllers/impact_cards/initiatives_controller.rb
# frozen_string_literal: true

module ImpactCards
  # Controller for Initiatives, nested under ImpactCards
  class InitiativesController < ApplicationController
    sidebar_item :impact_cards

    def show
      @impact_card = Scorecard.find(params[:impact_card_id])
      authorize(@impact_card, :show?)

      @initiative = @impact_card.initiatives.find(params[:id])
      authorize(@initiative, :edit?)

      @focus_areas_groups = FocusAreaGroup
                            .where(scorecard_type: @impact_card.type, account_id: @impact_card.account_id)
                            .order(:position)

      @grouped_checklist_items = @initiative.checklist_items_ordered_by_ordered_focus_area
    end
  end
end

app/controllers/initiatives/imports_controller.rb
# frozen_string_literal: true

module Initiatives
  # Imports for Initiatives
  class ImportsController < ApplicationController
    before_action :require_account_selected, only: %i[new create edit update] # rubocop:disable Rails/LexicallyScopedActionFilter
    before_action :set_initiatives_import, only: %i[show edit update destroy] # rubocop:disable Rails/LexicallyScopedActionFilter

    def new
      @initiatives_import = current_account.initiatives_imports.build(
        card_type: scorecard_type_from_scope(params[:scope])
      )
      authorize @initiatives_import
    end

    def create # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
      @initiatives_import = current_account.initiatives_imports.build(
        initiatives_import_params.merge(user: current_user)
      )
      authorize @initiatives_import

      if @initiatives_import.save && @initiatives_import.process(current_account)
        redirect_to initiatives_path, notice: 'Initiative records successfully imported.'
      else
        render :new
      end

      @initiatives_import.destroy
      file_system = Shrine.storages[:cache]
      file_system.clear! { |path| path.mtime < Time.zone.now - 1.hour }
    end

    def update
      if @initiatives_import.update(initiatives_import_params)
        redirect_to @initiatives_import, notice: 'Import was successfully updated.'
      else
        render :edit
      end
    end

    private

    def set_initiatives_import
      @initiatives_import = Initiatives::Import.find(params[:id])
      authorize @initiatives_import
    end

    def initiatives_import_params
      params.fetch(:initiatives_import, {}).permit(:import, :card_type)
    end

    def card_type_from_scope
      params[:scope].split('_').first
    end

    def scorecard_type_from_scope(scope)
      case scope
      when 'transition' then 'TransitionCard'
      when 'sdgs_alignment_cards' then 'SustainableDevelopmentGoalAlignmentCard'
      else
        current_account.default_scorecard_type&.name || 'TransitionCard'
      end
    end
  end
end

app/helpers/initiatives_helper.rb
# frozen_string_literal: true

# Helper methods for presenting initiative data
module InitiativesHelper
  def applicable_date_range(initiative)
    return '' if initiative.started_at.blank? && initiative.finished_at.blank?

    start_date = initiative.started_at&.strftime('%b %Y')
    end_date = initiative.finished_at&.strftime('%b %Y')

    return "Starts at #{start_date}" if end_date.blank?
    return "Ends at #{end_date}" if start_date.blank?

    safe_join([start_date, end_date], ' to ')
  end

  def scorecard_label(initiative) # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    if initiative.new_record? || initiative.scorecard.nil?
      current_account.scorecard_types.map { |type| type.model_name.human }
                     .join(' / ')
    else
      safe_join(
        [
          content_tag(:span, initiative.scorecard.model_name.human.to_s, style: 'margin-right: 10px'),
          link_to(
            content_tag(
              :i,
              '',
              class: 'fa fa-external-link'
            ),
            transition_card_path(initiative.scorecard),
            id: 'initiative-detail-scorecard-link'
          )
        ]
      )
    end
  end

  def initiatives_characteristics_title(initiative)
    case initiative.scorecard.type
    when 'TransitionCard' then 'Initiative Characteristics'
    when 'SustainableDevelopmentGoalAlignmentCard' then 'Initiative SDGs Targets'
    end
  end

  def mail_to_contact_email(initiative)
    return '' if initiative&.contact_email.blank?

    mail_to initiative.contact_email, initiative.contact_email, class: 'text-blue-500 hover:text-blue-700 underline'
  end

  def link_to_video_tutorial(video_tutorial) # rubocop:disable Metrics/MethodLength
    return '' if video_tutorial.blank?

    link_to(
      video_tutorial_path(video_tutorial),
      class: 'video-tutorial-wrapper',
      data: {
        video_tutorial_link: video_tutorial_path(video_tutorial),
        video_tutorial_title: video_tutorial.name
      }
    ) do
      safe_join([content_tag(:i, '', class: 'fa fa-youtube-play')])
    end
  end

  def linked_initiative_warning(initiative)
    return '' if initiative.blank?
    return '' if initiative.scorecard.blank?

    return '' unless initiative.new_record?
    return '' unless initiative.scorecard.linked?
    return '' if initiative.linked_initiative.present?

    content_tag(:div, class: 'form-group row alert alert-warning') do
      content_tag(:strong, 'Note: ', class: 'mr-1') +
        "This initiative belongs to a linked #{initiative.scorecard.model_name.human}. " \
        'Saving this initiative will automaically create a linked initiative in the other card.'
    end
  end

  def initiative_scorecard_types
    current_account.scorecard_types.map do |scorecard_type|
      [scorecard_type.model_name.human.pluralize, scorecard_type.name]
    end
  end

  private

  # SMELL: Duplicate of code in initiatives_controller.rb
  def scorecard_type_from_params(params)
    if params[:scope].blank? || !params[:scope].in?(%w[transition_cards sdgs_alignment_cards])
      current_account.default_scorecard_type
    else
      case params[:scope].to_sym
      when :sdgs_alignment_cards then SustainableDevelopmentGoalAlignmentCard
      when :transition_cards then TransitionCard
      end
    end
  end
end

app/views/initiatives/_checklist_item_description.html.erb
<%- if checklist_item.characteristic.description.present? %>
  <%= 
    link_to(
      description_characteristic_path(checklist_item.characteristic), 
      class: 'remote-link description-characteristic-link',
      data: {
        toggle: "tooltip",
        placement: "top", 
        title: "More information" 
      }
    ) do
      safe_join([content_tag(:i, '', class: "fas fa-info-circle")])
    end
  %>  
<%- end -%>

app/views/initiatives/_checklist_items.html.erb
<div class="tab-pane active" id="checklist-items-tab">
  <div class="container mx-auto">
    <div class="row tab-content-header p-3 flex justify-between items-center">
      <div class="col-sm">
        <div class="float-left pt-1">
          <h3 class="text-lg font-semibold"><%= initiatives_characteristics_title(@initiative) %></h3>
        </div>
        <div class="float-right">
          <%= link_to "#{display_scorecard_model_name(@initiative.scorecard)} Details", impact_card_path(@initiative.scorecard), class: 'btn btn-primary float-right bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600' %>
        </div>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="box-group" id="accordion">
        <% @focus_areas_groups.each do |focus_area_group| %>
          <div class="initiative-characteristics-container">
            <div class="focus-area-group-container">
              <h4 class="focus-area-group-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapsable-focus-area-group-<%= focus_area_group.id %>">
                  <%= focus_area_group.name %>
                  <%= link_to_video_tutorial(focus_area_group.video_tutorial) %>
                </a>
              </h4>
            </div>
            <div id="collapsable-focus-area-group-<%= focus_area_group.id %>" class="panel-collapse collapse <%= "show" if focus_area_group == @focus_areas_groups.first %> ">
              <% focus_area_group.focus_areas.order(:position).each do |focus_area| %>
                <div class="box-body">
                  <h3 class="focus-area">
                    <%- if @initiative.scorecard.type == 'TransitionCard' -%>
                      <%= focus_area.name %>
                      <%= link_to_video_tutorial(focus_area.video_tutorial) %>
                    <%- else -%>
                      <a data-toggle="collapse" data-parent="#collapsable-focus-area-group-<%= focus_area_group.id %>" href="#collapsable-focus-area-<%= focus_area.id %>">
                        <%= focus_area.name %>
                        <%= link_to_video_tutorial(focus_area.video_tutorial) %>
                      </a>
                    <%- end -%>
                  </h3>
                  <% checklist_items = @grouped_checklist_items.to_a.find_all { |ci| ci.characteristic.focus_area.id == focus_area.id } %>
                  <div id="collapsable-focus-area-<%= focus_area.id %>" class="panel-collapse collapse <%= "show" if @initiative.scorecard.type == 'TransitionCard' || focus_area == focus_area_group.focus_areas.first %> ">
                    <ul class="checklist-items">
                      <% checklist_items.each do |checklist_item| %>
                        <div
                            data-controller="comments"
                            data-load-path="<%=edit_checklist_item_path(checklist_item)%>"
                            data-state-path="<%=checklist_item_path(checklist_item)%>"
                        >
                          <li>
                            <label>
                              <%= checklist_item_badge(checklist_item) %>

                              <span class="characteristic-name <%= current_comment_status_style(checklist_item) %>" data-comments-target="characteristic">
                                <%= link_to(
                                      '#characteristic_comment',
                                      class: 'characteristic-comment',
                                      data: {
                                        action: "comments#open",
                                        id: checklist_item.id,
                                        initiative_id: checklist_item.initiative_id
                                      }
                                    )  do
                                      checklist_item.characteristic.name
                                    end
                                %>
                              </span>
                              <%= link_to(
                                '#characteristic_comment',
                                class: 'characteristic-comment',
                                data: {
                                  action: "comments#open",
                                  id: checklist_item.id,
                                  initiative_id: checklist_item.initiative_id,
                                  toggle: "tooltip",
                                  placement: "top",
                                  title: "Edit comments"
                                }
                              ) do
                                safe_join([content_tag(:i, '', class: "fa fa-comments-o")])
                              end %>
                              <%= render 'checklist_item_video_tutorial', video_tutorial: checklist_item.characteristic.video_tutorial %>
                              <%= render 'checklist_item_description', checklist_item: checklist_item %>
                            </label>

                            <div data-comments-target="form"></div>
                          </li>
                        </div>
                      <%- end -%>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/initiatives/_form.html.erb
<div class="mx-auto max-w-6xl">
  <h1 class="text-2xl/8 font-semibold text-zinc-950 sm:text-xl/8 dark:text-white">Edit Initiative</h1>

  <%= form_with model: @initiative, class: 'mx-auto max-w-6xl', data: { turbo: false } do |form| %>
    <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 dark:border-white/10 pb-12 md:grid-cols-3">
      <div>
        <h2 class="text-base/7 font-semibold text-zinc-950 dark:text-white">General Settings</h2>
        <p class="mt-1 text-sm/6 text-gray-600">Name and description</p>
      </div>

      <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2">
        <div class="sm:col-span-4">
          <%= form.label :name %>
          <div class="mt-2">
            <%= form.text_field :name, placeholder: 'Initiative name', class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" %>
          </div>
        </div>

        <div class="col-span-full">
          <%= form.label :description %>
          <div class="mt-2">
            <%= form.text_area :description, rows: 3, placeholder: 'Initiative description', class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" %>
          </div>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 dark:border-white/10 pb-12 md:grid-cols-3">
      <div>
        <h3 class="pl-10 text-sm font-semibold text-zinc-950 dark:text-white text-right">Subsystem Tags</h3>
        <p class="mt-1 text-sm/6 text-gray-600 text-right">Identify relevant subsystem tags for this initiative.</p>
      </div>
      <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2" id="initiatives-subsystem-tags" data-controller="initiatives-subsystem-tags">
        <%= render 'subsystem_tag_fields' %>
        <div class="sm:col-span-6" data-initiatives-subsystem-tags-target="initiativesSubsystemTags">
          <%= form.fields_for :initiatives_subsystem_tags do |initiatives_subsystem_tags_form| %>
            <div class="flex items-center space-x-4 mt-3">
              <%= initiatives_subsystem_tags_form.collection_select :subsystem_tag_id, policy_scope(SubsystemTag), :id, :name, { include_blank: 'Select a subsystem tag' } %>
              <%= link_to 'Remove', '#', class: 'text-red-500', data: { action: 'initiatives-subsystem-tags#removeTag' } %>
            </div>
          <% end %>
        </div>

        <div class="sm:col-span-6 mt-2">
          <%= link_to 'Add Subsystem Tag', '#', id: 'add-subsystem-tag', class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500', data: { action: 'initiatives-subsystem-tags#addTag' } %>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 dark:border-white/10 pb-12 md:grid-cols-3">
      <div>
        <h3 class="text-sm font-semibold text-zinc-950 dark:text-white text-right">Contact Details</h3>
        <p class="mt-1 text-sm/6 text-gray-600 text-right">Enter the main contact for this initiative (optional).</p>
      </div>

      <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2">
        <div class="sm:col-span-3">
          <%= form.label :contact_name %>
          <div class="mt-2">
            <%= form.text_field :contact_name %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :contact_email %>
          <div class="mt-2">
            <%= form.text_field :contact_email %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :contact_website %>
          <div class="mt-2">
            <%= form.text_field :contact_website %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :contact_position %>
          <div class="mt-2">
            <%= form.text_field :contact_position %>
          </div>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 dark:border-white/10 pb-12 md:grid-cols-3">
      <div>
        <h3 class="pl-10 text-sm font-semibold text-zinc-950 dark:text-white text-right">Applicable Date Range</h3>
        <p class="mt-1 text-sm/6 text-gray-600 text-right">Optional</p>
      </div>

      <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2">
        <div class="sm:col-span-3">
          <%= form.label :started_at %>
          <div class="mt-2">
            <%= form.date_field :started_at %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :finished_at %>
          <div class="mt-2">
            <%= form.date_field :finished_at %>
          </div>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 dark:border-white/10 pb-12 md:grid-cols-3">
      <div>
        <h3 class="pl-10 text-sm font-semibold text-zinc-950 dark:text-white text-right">Stakeholders</h3>
        <p class="mt-1 text-sm/6 text-gray-600 text-right">Identify who might be interested in this initiative.</p>
      </div>
      <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2" id="initiatives-organisations" data-controller="initiatives-organisations">
        <%= render 'organisation_fields' %>
        <div class="sm:col-span-6" data-initiatives-organisations-target="initiativesOrganisations">
          <%= form.fields_for :initiatives_organisations do |initiatives_organisations_form| %>
            <div class="flex items-center space-x-4 mt-3">
              <%= initiatives_organisations_form.collection_select :organisation_id, policy_scope(Organisation), :id, :name, { include_blank: 'Select a stakeholder' } %>
              <%= link_to 'Remove', '#', class: 'text-red-500', data: { action: 'initiatives-organisations#removeTag' } %>
            </div>
          <% end %>
        </div>

        <div class="sm:col-span-6 mt-2">
          <%= link_to 'Add Stakeholder', '#', id: 'add-organisation', class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500', data: { action: 'initiatives-organisations#addTag' } %>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-1 gap-x-8 gap-y-10 border-b border-gray-900/10 dark:border-white/10 pb-12 md:grid-cols-3">
      <div>
        <h3 class="text-sm font-semibold text-zinc-950 dark:text-white text-right">Notes</h3>
        <p class="mt-1 text-sm/6 text-gray-600 text-right">Any additional details (optional).</p>
      </div>

      <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6 md:col-span-2">
        <div class="sm:col-span-3">
          <%= form.label :notes %>
          <div class="mt-2">
            <%= form.text_area :notes %>
          </div>
        </div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%- if @initiative.persisted? %>
        <%= link_to 'Cancel', initiative_path(@initiative), class: "text-sm/6 font-semibold text-gray-900 dark:text-white" %>
      <% else %>
        <%= link_to 'Cancel', initiatives_path, class: "text-sm/6 font-semibold text-gray-900 dark:text-white" %>
      <% end %>
      <%= form.submit 'Save' %>
    </div>

  <% end %>
</div>

app/views/initiatives/show.html.erb
<%= render 'labels/stylesheet', labels: @subsystem_tags %>
<div class="mx-auto max-w-6xl">

  <div class="flex flex-wrap items-end justify-between gap-4">
    <div class="w-full">
      <h1 class="text-2xl/8 font-semibold text-zinc-950 sm:text-xl/8 dark:text-white">Initiative Details</h1>

      <div class="flex justify-between items-start mt-4">
        <div class="flex gap-6 py-6">
        <%= render partial: 'resource_summary', locals: { name: @initiative.name, background_color: 'bg-sky-600' } %>
          <div class="space-y-1.5">
            <div class="text-base/6 font-semibold dark:text-white">
              <%= @initiative.name %>
            </div>
            <div class="text-xs/6 text-zinc-600">
              <%= @initiative.scorecard&.name.presence || 'MISSING' %>
            </div>

            <%- if @initiative.subsystem_tags.present? %>
              <div class="flex space-x-4">
                <%- @initiative.subsystem_tags.each do |subsystem_tag| %>
                  <%= render 'label_badge', label: subsystem_tag %>
                <%- end %>
              </div>
            <%- end %>
          </div>
        </div>
        <div class="relative">
          <div class="flex justify-end items-start mb-4">
            <%= link_to_primary 'Edit', edit_initiative_path(@initiative), class: 'inline-flex items-start px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
          </div>
        </div>
      </div>
    </div>


    <div class="mx-auto max-w-6xl w-full">
      <div class="mt-1 border-t border-gray-100">
        <dl class="grid grid-cols-1 gap-y-6 px-4 py-6 w-full">
          <div class="flex items-start space-x-4">
            <dt class="text-sm/6 font-medium text-gray-900 min-w-48">Description</dt>
            <dd class="text-sm/6 text-gray-700"><%= @initiative.description %></dd>
          </div>
          <div class="flex items-start space-x-4">
            <dt class="text-sm/6 font-medium text-gray-900 min-w-48">Contact Details</dt>
            <dd class="text-sm/6 text-gray-700 sm:col-span-2 sm:mt-0">
              <dl class="grid grid-cols-1 sm:grid-cols-2">
                <div class="pb-6 sm:col-span-1 sm:px-0">
                  <dt class="text-sm/6 font-medium text-gray-900">Contact name</dt>
                  <dd class="mt-1 text-sm/6 text-gray-700 sm:mt-2"><%= @initiative.contact_name %></dd>
                </div>
                <div class="px-4 pb-6 sm:col-span-1 sm:px-0">
                  <dt class="text-sm/6 font-medium text-gray-900">Contact email</dt>
                  <dd class="mt-1 text-sm/6 text-gray-700 sm:mt-2"><%= mail_to_contact_email(@initiative) %></dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                  <dt class="text-sm/6 font-medium text-gray-900">Contact website</dt>
                  <dd class="mt-1 text-sm/6 text-gray-700 sm:mt-2"><%= link_to_external_url(@initiative.contact_website) %></dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                  <dt class="text-sm/6 font-medium text-gray-900">Contact position</dt>
                  <dd class="mt-1 text-sm/6 text-gray-700 sm:mt-2"><%= @initiative.contact_position %></dd>
                </div>
              </dl>
            </dd>
          </div>
          <div class="flex items-start space-x-4">
            <dt class="text-sm/6 font-medium text-gray-900 min-w-48">Applicable Date Range</dt>
            <dd class="text-sm/6 text-gray-700"><%= applicable_date_range(@initiative) %></dd>
          </div>

          <div class="flex items-start space-x-4">
            <dt class="text-sm/6 font-medium text-gray-900 min-w-48">Stakeholders</dt>
            <dd class="mt-2 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
              <ul role="list" class="divide-y divide-gray-100 rounded-md border border-gray-200">
                <%- @initiative.organisations.each do |stakeholder| %>
                <li class="flex items-start justify-between py-4 pl-4 pr-5 text-sm/6">
                  <div class="flex w-0 flex-1 items-start">
                    <%= stakeholder.name %>
                  </div>
                  <div class="ml-4 shrink-0">
                    <%= link_to 'View', organisation_path(stakeholder), class: 'font-medium text-indigo-600 hover:text-indigo-500' %>
                  </div>
                </li>
                <% end %>
              </ul>
            </dd>
          </div>
        </dl>
      </div>
    </div>

  </div>
</div>