config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :impact_cards do
    resources :initiatives, only: [:show], controller: 'impact_cards/initiatives'
  end

  namespace :initiatives do
    resources :imports, only: %i[new create update]
  end

  namespace :labels do
    resources :communities
    resources :stakeholder_types
    resources :subsystem_tags
    resources :wicked_problems
  end

  resources :checklist_items, only: %i[show edit update]

  namespace :organisations do
    resources :imports, only: %i[new create update]
  end

  namespace :transition_card_comments do
    resources :imports, only: %i[new create update], controller: '/scorecard_comments/imports'
  end

  # TODO: Fix this route once we have a proper transition_card_comments import
  namespace :sustainable_development_goal_alignment_card_comments do
    resources :imports, only: %i[new create update], controller: '/scorecard_comments/imports'
  end

  devise_for :users, controllers: {
    invitations: 'invitations'
   }

  resources :accounts do
    member do
      get 'switch'
    end
  end

  resources :characteristics do
    member do
      get 'description'
    end
  end

  resources :focus_area_groups
  resources :focus_areas
  resources :initiatives do
    resources :checklist_items do
      member do
        post 'update_comment'
        post 'create_comment'
        get 'comment_status'
      end
    end
    get 'linked'
  end
  resources :initiatives_organisations
  resources :initiatives_subsystem_tags
  resources :organisations

  resources :transition_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end
  end

  resources :sustainable_development_goal_alignment_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'targets_network_map'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end

    resources :characteristics,
              only: [:show],
              controller: 'sustainable_development_goal_alignment_cards',
              action: 'characteristic'
  end

  resources :ecosystem_maps do
    resources :organisations, only: [:show], controller: 'ecosystem_maps/organisations'
  end

  resources :shared,
            constraints: {
              id: /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(\d+)/
            },
            only: [:show] do
    member do
      get 'targets_network_map'
    end

    resources :characteristics, only: [:show], controller: 'shared', action: 'characteristic'
  end

  resources :users do
    post :stop_impersonating, on: :collection

    post :impersonate, on: :member

    member do
      get 'undelete'
      get 'resend_invitation'
      get 'remove_from_account'
    end
  end

  resources :reports, only: [:index] do
    collection do
      post 'initiatives'
      post 'stakeholders'
      get 'scorecard_activity'
      post 'scorecard_activity'
      post 'transition_card_stakeholders'
      post 'scorecard_comments'
      get 'scorecard_comments'
      get 'transition_card_activity'
      post 'transition_card_activity'
      get 'subsystem_summary'
      post 'subsystem_summary'
      get 'cross_account_percent_actual'
      post 'cross_account_percent_actual'
      get 'cross_account_percent_actual_by_focus_area'
      post 'cross_account_percent_actual_by_focus_area'
      get 'cross_account_percent_actual_by_focus_area_tabbed'
      post 'cross_account_percent_actual_by_focus_area_tabbed'
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'reports', to: 'reports#index'
  get 'activities', to: 'activities#index'
  get 'contributors', to: 'home#contributors'

  namespace :system do
    resources :stakeholder_types
  end

  root to: 'home#index'
end

app/controllers/shared_controller.rb
# frozen_string_literal: true

# Controller for managing shared impact cards
class SharedController < ApplicationController
  def show # rubocop:disable Metrics/MethodLength
    response.headers.delete('X-Frame-Options')

    load_scorecard_and_supporting_data

    if @scorecard.present?
      if params[:iframe] == 'true'
        render('show_iframe', layout: false)
      else
        render(layout: 'embedded')
      end

    else
      render(file: 'public/404.html', layout: 'embedded', status: :not_found)
    end
  end

  def characteristic # rubocop:disable Metrics/AbcSize
    @scorecard = Scorecard.find_by(shared_link_id: params[:shared_id])

    @characteristic = Characteristic.find(params[:id])

    checklist_items =
      ChecklistItem
      .where(characteristic: @characteristic, initiative: @scorecard.initiatives)
      .includes(:checklist_item_comments)
      .select { |item| item.status == 'actual' }

    @initiatives = checklist_items.map(&:initiative).sort_by(&:name)

    @targets = TargetsNetworkMapping.where(characteristic: @characteristic).map(&:focus_area).uniq.sort_by(&:name)

    render('sustainable_development_goal_alignment_cards/show_tabs/characteristics/show', layout: false)
  end

  # SMELL: Duplicate of code in scorecards_controller.rb
  def targets_network_map
    @scorecard = Scorecard.find_by(shared_link_id: params[:id])

    respond_to do |format|
      format.json do
        data = EcosystemMaps::TargetsNetwork.new(@scorecard)
        render(json: { data: { nodes: data.nodes, links: data.links } })
      end
    end
  end

  private

  def load_scorecard_and_supporting_data # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    @scorecard = Scorecard.find_by(shared_link_id: params[:id])

    return if @scorecard.blank?

    @initiatives = @scorecard.initiatives.order(:name)
    @organisations = @initiatives.filter_map(&:organisations).flatten.uniq.sort_by(&:name)

    @results = ScorecardGrid.execute(@scorecard, nil, [])
    @focus_areas = FocusArea.per_scorecard_type_for_account(
      @scorecard.type,
      @scorecard.account
    ).ordered_by_group_position

    @characteristics = Characteristic.per_scorecard_type_for_account(
      @scorecard.type,
      @scorecard.account
    ).includes(focus_area: :focus_area_group).order('focus_areas.position, characteristics.position')
  end
end

app/views/layouts/shared/_favicons.html.erb
<%= favicon_link_tag 'favicons/android-icon-36x36.png' %>
<%= favicon_link_tag 'favicons/android-icon-48x48.png' %>
<%= favicon_link_tag 'favicons/android-icon-72x72.png' %>
<%= favicon_link_tag 'favicons/android-icon-96x96.png' %>
<%= favicon_link_tag 'favicons/android-icon-144x144.png' %>
<%= favicon_link_tag 'favicons/android-icon-192x192.png' %>
<%= favicon_link_tag 'favicons/apple-icon-57x57.png' %>
<%= favicon_link_tag 'favicons/apple-icon-60x60.png' %>
<%= favicon_link_tag 'favicons/apple-icon-72x72.png' %>
<%= favicon_link_tag 'favicons/apple-icon-76x76.png' %>
<%= favicon_link_tag 'favicons/apple-icon-114x114.png' %>
<%= favicon_link_tag 'favicons/apple-icon-120x120.png' %>
<%= favicon_link_tag 'favicons/apple-icon-144x144.png' %>
<%= favicon_link_tag 'favicons/apple-icon-152x152.png' %>
<%= favicon_link_tag 'favicons/apple-icon-180x180.png' %>
<%= favicon_link_tag 'favicons/apple-icon-precomposed.png' %>
<%= favicon_link_tag 'favicons/apple-icon.png' %>
<%= favicon_link_tag 'favicons/favicon-16x16.png' %>
<%= favicon_link_tag 'favicons/favicon-32x32.png' %>
<%= favicon_link_tag 'favicons/favicon-96x96.png' %>
<%= favicon_link_tag 'favicons/favicon.ico' %>
<%= favicon_link_tag 'favicons/manifest.json' %>
<%= favicon_link_tag 'favicons/ms-icon-70x70.png' %>
<%= favicon_link_tag 'favicons/ms-icon-144x144.png' %>
<%= favicon_link_tag 'favicons/ms-icon-150x150.png' %>
<%= favicon_link_tag 'favicons/ms-icon-310x310.png'  %>

app/views/layouts/shared/_flash_messages.html.erb
<% if flash.any? %>
  <div class='inset-0 items-start justify-end'>
    <div class='flex flex-col items-center justify-center'>
      <% flash.each do |type, message| %>
        <%= render FlashMessage::Component.new(type: type, message: message) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/shared/_modal.html.erb
<div id="default-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/layouts/shared/_sidebar_desktop.html.erb
<div class="fixed inset-y-0 left-0 w-60 max-lg:hidden bg-zinc-950">
  <div class="flex h-full min-h-0 flex-col">
    <div class="flex items-center border-b border-zinc-950/5 p-4 dark:border-white/5 mt-2.5">
      <%= image_tag 'logo-small.png', class: 'h-7 w-7', alt: "Logo for the 'Obsekio'" %>
      <span class="ml-2 text-white font-extrabold text-lg">Obsekio</span>
    </div>
    <nav class="flex h-full min-h-0 flex-col">
      <ul role="list" class="flex flex-1 flex-col overflow-y-auto p-4">
        <li>
          <ul role="list" class="-mx-2 space-y-1">
            <%= render_sidebar_item title: 'Home', path: root_path, icon: :home, active_group: :home %>
            <%= render_sidebar_item title: 'Impact Cards', path: impact_cards_path, icon: :impact_cards, active_group: :impact_cards %>
            <%= render_sidebar_item title: 'Initiatives', path: initiatives_path, icon: :initiatives, active_group: :initiatives %>
            <%= render_sidebar_item title: 'Stakeholders', path: organisations_path, icon: :stakeholders, active_group: :stakeholders %>
            <%= render_sidebar_item title: 'Reports', path: reports_path, icon: :reports, active_group: :reports %>
            <%= render_sidebar_item title: 'Team', path: users_path, icon: :teams, active_group: :teams %>
          </ul>
        </li>
        <li>
          <div class="text-xs font-semibold leading-6 text-gray-400 mt-8">Labels</div>
          <ul role="list" class="-mx-2 mt-2 space-y-1">
            <%= render_sidebar_item title: 'Communities', path: labels_communities_path, icon: :tags, active_group: :communities %>
            <%= render_sidebar_item title: 'Problems / Opportunities', path: labels_wicked_problems_path, icon: :tags, active_group: :problems %>
            <%= render_sidebar_item title: 'Stakeholder Types', path: labels_stakeholder_types_path, icon: :tags, active_group: :stakeholder_types %>
            <%= render_sidebar_item title: 'Subsystem Tags', path: labels_subsystem_tags_path, icon: :tags, active_group: :subsystem_tags %>
          </ul>
        </li>
        <li class="mt-auto">
          <%= render_dropdown_menu do %>
            <%= dropdown_menu_trigger do %>
              <div class="group flex justify-between gap-x-3 rounded-md -mx-2 p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                <div class="flex items-center">
                  <%= render_icon :user_profile %>
                  <span class="ml-2">Your Profile</span>
                </div>
                <div class="ml-auto flex items-center">
                  <%= render_icon :menu_up %>
                </div>
              </div>
            <% end %>

            <%= dropdown_menu_content do %>
             <%=
                dropdown_menu_item do
                  link_to "#{current_account.name} &checkmark;".html_safe, current_account, class: "block w-full text-sm"
                end
              %>
              <%- current_user.accounts.where.not(id: current_account.id).limit(4).each do |account| %>
                <%= dropdown_menu_item do %>
                  <%= link_to account.name, switch_account_path(account), class: "block w-full text-sm" %>
                <% end %>
              <% end %>

              <%=
                dropdown_menu_item do
                  link_to "Other accounts...", accounts_path, class: "block w-full text-sm"
                end
              %>
              <hr/>
              <%=
                dropdown_menu_item do
                  link_to "Settings", root_path, class: "block w-full text-sm"
                end
              %>

              <%=
                dropdown_menu_item do
                  link_to "Dark mode &checkmark;".html_safe, '', data: { controller: 'theme', theme_target: 'toggle', action: 'theme#toggle' }, class: 'block w-full'
                end
              %>
              <hr/>
              <%- if current_user != true_user %>
                <%=
                  dropdown_menu_item do
                    link_to "Stop impersonating", stop_impersonating_users_path, data: { turbo_method: "post" }, class: "block w-full text-sm"
                  end
                %>
              <% end %>

              <%=
                dropdown_menu_item do
                  link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "block w-full text-sm font-semibold"
                end
              %>
            <% end %>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/shared/_sidebar_item.html.erb
<%
  if active
    options = {
      class: "group flex gap-x-3 rounded-md bg-gray-800 p-2 text-sm font-semibold leading-6 text-white",
      aria: { current: "page" }
    }
  else
    options = { class: "group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white" }
  end
%>

<li>
  <%= link_to path, options do %>
    <%= render_icon icon %>
    <%= title %>
    <%- if count.present? %>
      <span class="ml-auto w-9 min-w-max whitespace-nowrap rounded-full bg-gray-900 px-2.5 py-0.5 text-center text-xs font-medium leading-5 text-white ring-1 ring-inset ring-gray-700" aria-hidden="true"><%= count %></span>
    <%- end %>
  <% end %>
</li>

app/views/layouts/shared/_sidebar_mobile.html.erb
<!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
<div class="relative z-50 lg:hidden" role="dialog" aria-modal="true">
  <!--
    Off-canvas menu backdrop, show/hide based on off-canvas menu state.

    Entering: "transition-opacity ease-linear duration-300"
      From: "opacity-0"
      To: "opacity-100"
    Leaving: "transition-opacity ease-linear duration-300"
      From: "opacity-100"
      To: "opacity-0"
  -->
  <div class="fixed inset-0 bg-gray-900/80" aria-hidden="true"></div>

  <div class="fixed inset-0 flex">
    <!--
      Off-canvas menu, show/hide based on off-canvas menu state.

      Entering: "transition ease-in-out duration-300 transform"
        From: "-translate-x-full"
        To: "translate-x-0"
      Leaving: "transition ease-in-out duration-300 transform"
        From: "translate-x-0"
        To: "-translate-x-full"
    -->
    <div class="relative mr-16 flex w-full max-w-xs flex-1">
      <!--
        Close button, show/hide based on off-canvas menu state.

        Entering: "ease-in-out duration-300"
          From: "opacity-0"
          To: "opacity-100"
        Leaving: "ease-in-out duration-300"
          From: "opacity-100"
          To: "opacity-0"
      -->
      <div class="absolute left-full top-0 flex w-16 justify-center pt-5">
        <button type="button" class="-m-2.5 p-2.5">
          <span class="sr-only">Close sidebar</span>
          <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- Sidebar component, swap this element with another sidebar if you like -->
      <div class="flex grow flex-col gap-y-5 overflow-y-auto bg-gray-900 px-6 pb-4 ring-1 ring-white/10">
        <div class="flex h-16 shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <nav class="flex flex-1 flex-col">
          <ul role="list" class="flex flex-1 flex-col gap-y-7">
            <li>
              <ul role="list" class="-mx-2 space-y-1">
                <li>
                  <!-- Current: "bg-gray-800 text-white", Default: "text-gray-400 hover:text-white hover:bg-gray-800" -->
                  <a href="#" class="group flex gap-x-3 rounded-md bg-gray-800 p-2 text-sm font-semibold leading-6 text-white">
                    <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                    </svg>
                    Dashboard
                  </a>
                </li>
                <li>
                  <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                    <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z" />
                    </svg>
                    Team
                  </a>
                </li>
                <li>
                  <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                    <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
                    </svg>
                    Projects
                  </a>
                </li>
                <li>
                  <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                    <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
                    </svg>
                    Calendar
                  </a>
                </li>
                <li>
                  <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                    <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125 1.125 0 01-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H6.75a9.06 9.06 0 011.5.124m7.5 10.376h3.375c.621 0 1.125-.504 1.125-1.125V11.25c0-4.46-3.243-8.161-7.5-8.876a9.06 9.06 0 00-1.5-.124H9.375c-.621 0-1.125.504-1.125 1.125v3.5m7.5 10.375H9.375a1.125 1.125 0 01-1.125-1.125v-9.25m12 6.625v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5a1.125 1.125 0 01-1.125-1.125v-1.5a3.375 3.375 0 00-3.375-3.375H9.75" />
                    </svg>
                    Documents
                  </a>
                </li>
                <li>
                  <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                    <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6a7.5 7.5 0 107.5 7.5h-7.5V6z" />
                      <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 10.5H21A7.5 7.5 0 0013.5 3v7.5z" />
                    </svg>
                    Reports
                  </a>
                </li>
              </ul>
            </li>
            <li>
              <div class="text-xs font-semibold leading-6 text-gray-400">Your teams</div>
              <ul role="list" class="-mx-2 mt-2 space-y-1">
                <li>
                  <!-- Current: "bg-gray-800 text-white", Default: "text-gray-400 hover:text-white hover:bg-gray-800" -->
                  <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                    <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border border-gray-700 bg-gray-800 text-[0.625rem] font-medium text-gray-400 group-hover:text-white">H</span>
                    <span class="truncate">Heroicons</span>
                  </a>
                </li>
                <li>
                  <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                    <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border border-gray-700 bg-gray-800 text-[0.625rem] font-medium text-gray-400 group-hover:text-white">T</span>
                    <span class="truncate">Tailwind Labs</span>
                  </a>
                </li>
                <li>
                  <a href="#" class="group flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                    <span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg border border-gray-700 bg-gray-800 text-[0.625rem] font-medium text-gray-400 group-hover:text-white">W</span>
                    <span class="truncate">Workcation</span>
                  </a>
                </li>
              </ul>
            </li>
            <li class="mt-auto">
              <a href="#" class="group -mx-2 flex gap-x-3 rounded-md p-2 text-sm font-semibold leading-6 text-gray-400 hover:bg-gray-800 hover:text-white">
                <svg class="h-6 w-6 shrink-0" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z" />
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                Settings
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</div>