config/routes.rb
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :impact_cards do
    resources :initiatives, only: [:show], controller: 'impact_cards/initiatives'
  end

  namespace :initiatives do
    resources :imports, only: %i[new create update]
  end

  namespace :labels do
    resources :communities
    resources :stakeholder_types
    resources :subsystem_tags
    resources :wicked_problems
  end

  resources :checklist_items, only: %i[show edit update]

  namespace :organisations do
    resources :imports, only: %i[new create update]
  end

  namespace :transition_card_comments do
    resources :imports, only: %i[new create update], controller: '/scorecard_comments/imports'
  end

  # TODO: Fix this route once we have a proper transition_card_comments import
  namespace :sustainable_development_goal_alignment_card_comments do
    resources :imports, only: %i[new create update], controller: '/scorecard_comments/imports'
  end

  devise_for :users, controllers: {
    invitations: 'invitations'
   }

  resources :accounts do
    member do
      get 'switch'
    end
  end

  resources :characteristics do
    member do
      get 'description'
    end
  end

  resources :focus_area_groups
  resources :focus_areas
  resources :initiatives do
    resources :checklist_items do
      member do
        post 'update_comment'
        post 'create_comment'
        get 'comment_status'
      end
    end
    get 'linked'
  end
  resources :initiatives_organisations
  resources :initiatives_subsystem_tags
  resources :organisations

  resources :transition_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end
  end

  resources :sustainable_development_goal_alignment_cards do
    member do
      get 'show_shared_link'
      post 'copy'
      get 'copy_options'
      post 'merge'
      get 'merge_options'
      get 'ecosystem_maps_organisations'
      get 'activities'
      get 'targets_network_map'
      get 'linked_initiatives/:target_id', action: 'linked_initiatives', as: 'linked_initiatives'
    end

    resources :characteristics,
              only: [:show],
              controller: 'sustainable_development_goal_alignment_cards',
              action: 'characteristic'
  end

  resources :ecosystem_maps do
    resources :organisations, only: [:show], controller: 'ecosystem_maps/organisations'
  end

  resources :shared,
            constraints: {
              id: /([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(\d+)/
            },
            only: [:show] do
    member do
      get 'targets_network_map'
    end

    resources :characteristics, only: [:show], controller: 'shared', action: 'characteristic'
  end

  resources :users do
    post :stop_impersonating, on: :collection

    post :impersonate, on: :member

    member do
      get 'undelete'
      get 'resend_invitation'
      get 'remove_from_account'
    end
  end

  resources :reports, only: [:index] do
    collection do
      post 'initiatives'
      post 'stakeholders'
      get 'scorecard_activity'
      post 'scorecard_activity'
      post 'transition_card_stakeholders'
      post 'scorecard_comments'
      get 'scorecard_comments'
      get 'transition_card_activity'
      post 'transition_card_activity'
      get 'subsystem_summary'
      post 'subsystem_summary'
      get 'cross_account_percent_actual'
      post 'cross_account_percent_actual'
      get 'cross_account_percent_actual_by_focus_area'
      post 'cross_account_percent_actual_by_focus_area'
      get 'cross_account_percent_actual_by_focus_area_tabbed'
      post 'cross_account_percent_actual_by_focus_area_tabbed'
    end
  end

  get 'dashboard', to: 'dashboard#index'
  get 'reports', to: 'reports#index'
  get 'activities', to: 'activities#index'
  get 'contributors', to: 'home#contributors'

  namespace :system do
    resources :stakeholder_types
  end

  root to: 'home#index'
end

app/models/transition_card.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: scorecards
#
#  id                         :integer          not null, primary key
#  deleted_at                 :datetime
#  description                :string
#  name                       :string
#  share_ecosystem_map        :boolean          default(TRUE)
#  share_thematic_network_map :boolean          default(TRUE)
#  type                       :string           default("TransitionCard")
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  account_id                 :integer
#  community_id               :integer
#  linked_scorecard_id        :integer
#  shared_link_id             :string
#  wicked_problem_id          :integer
#
# Indexes
#
#  index_scorecards_on_account_id  (account_id)
#  index_scorecards_on_deleted_at  (deleted_at)
#  index_scorecards_on_type        (type)
#
class TransitionCard < Scorecard
end

app/controllers/transition_cards_controller.rb
# frozen_string_literal: true

# Controller for managing transition cards - to be deprecated in favour of ImpactCardsController
class TransitionCardsController < ImpactCardsController
  sidebar_item :impact_cards

  def scorecard_key_param
    :transition_card
  end

  def scorecard_class_name
    'TransitionCard'
  end
end

app/views/transition_cards/show_tabs/_grid.html.erb
<div class="bg-gray-900">
  <div class="mx-auto max-w-7xl">
    <div class="bg-gray-900 py-10">
      <div class="px-4 sm:px-6 lg:px-8">
        <div class="sm:flex sm:items-center">
          <div class="sm:flex-auto">
            <h1 class="text-base font-semibold leading-6 text-white">Users</h1>
            <p class="mt-2 text-sm text-gray-300">A list of all the users in your account including their name, title, email and role.</p>
          </div>
          <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
            <button type="button" class="block rounded-md bg-indigo-500 px-3 py-2 text-center text-sm font-semibold text-white hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Add user</button>
          </div>
        </div>
        <div class="mt-8 flow-root">
          <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
              <table class="min-w-full divide-y divide-gray-700">
                <thead>
                  <tr>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-white sm:pl-0">Name</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-white">Title</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-white">Email</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-white">Role</th>
                    <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                      <span class="sr-only">Edit</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-gray-800">
                  <tr>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-white sm:pl-0">Lindsay Walton</td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-300">Front-end Developer</td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-300">lindsay.walton@example.com</td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-300">Member</td>
                    <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                      <a href="#" class="text-indigo-400 hover:text-indigo-300">Edit<span class="sr-only">, Lindsay Walton</span></a>
                    </td>
                  </tr>

                  <!-- More people... -->
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transition_cards/show_tabs/_scorecard.html.erb
<div class="container-fluid" data-controller='transition-cards'>
  <div class="row tab-content-header p-3">
    <div class="col-sm">
      <div class="float-left">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
          </div>
          <input
            type="text"
            class="form-control"
            id="transition_card_select_date"
            autocomplete="off"
            data-scorecard-id="<%=@scorecard.id%>" placeholder="Select Date"
            <%= "data-selected-date=\"#{@selected_date}\"" unless @selected_date.blank? %>
          >
        </div>
      </div>
      <div class="float-left">
        <%= link_to('#', class: 'btn btn-primary', id: 'daterange-clear-btn', data: { toggle: "tooltip" }, title: "Clear date") do
          content_tag(:i, '', class: "fa fa-undo")
        end %>
      </div>

      <%- if policy(:sidebar).show_subsystem_tags_link? %>
        <div class="float-left" style="padding-right: 5px; padding-left: 5px;">
          <div class="input-group">

            <select multiple="multiple" class="form-control" id="subsystem-tags" style="min-width: 300px;" data-scorecard-id="<%=@scorecard.id%>">
              <%- @selected_tags.each do |selected_tag| %>
                  <option value="<%= selected_tag.id %>" selected="selected"><%= selected_tag.text %></option>
              <%- end %>
            </select>
          </div>
        </div>
      <%- end %>

      <div class="float-right">
        <%= render partial: '/scorecards/show_tabs/status_filter' %>

        <%- print_transition_card_path = if @selected_date
            transition_card_path(@scorecard, format: :pdf, selected_date: @selected_date, key: SecureRandom.urlsafe_base64(5))
          else
            transition_card_path(@scorecard, format: :pdf, key: SecureRandom.urlsafe_base64(5))
          end
        %>
        <%= link_to(print_transition_card_path, class: 'btn btn-primary', data: { toggle: "tooltip"}, title: "Print") do
          content_tag(:i, '', class: "fa fa-print")
        end %>
        <%= link_to(show_shared_link_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Share") do
          content_tag(:i, '', class: "fa fa-share-alt")
        end %>
        <% if policy(:scorecard).copy_options? %>
          <%= link_to(copy_options_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Copy") do
            content_tag(:i, '', class: "fa fa-files-o")
          end %>
        <% end %>
        <% if policy(:scorecard).merge_options? %>
          <%= link_to(merge_options_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Merge") do
            content_tag(:i, '', class: "fa fa-file-text-o")
          end %>
        <% end %>

      </div>
    </div>
  </div>
  <%= render partial: 'transition_cards/show_tabs/grid' %>
</div>

app/views/transition_cards/show_tabs/_transition_card.html.erb
<div class="container-fluid" data-controller='transition-cards'>
  <div class="row tab-content-header p-3">
    <div class="col-sm">
      <div class="float-left">
        <div class="input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
          </div>
          <input 
            type="text" 
            class="form-control" 
            id="transition_card_select_date"
            autocomplete="off"
            data-scorecard-id="<%=@scorecard.id%>" placeholder="Select Date"
            <%= "data-selected-date=\"#{@selected_date}\"" unless @selected_date.blank? %>
          >
        </div>
      </div>
      <div class="float-left">
        <%= link_to('#', class: 'btn btn-primary', id: 'daterange-clear-btn', data: { toggle: "tooltip" }, title: "Clear date") do
          content_tag(:i, '', class: "fa fa-undo")
        end %>
      </div>
      
      <%- if policy(:sidebar).show_subsystem_tags_link? %>
        <div class="float-left" style="padding-right: 5px; padding-left: 5px;">
          <div class="input-group">
          
            <select multiple="multiple" class="form-control" id="subsystem-tags" style="min-width: 300px;" data-scorecard-id="<%=@scorecard.id%>">
              <%- @selected_tags.each do |selected_tag| %>
                  <option value="<%= selected_tag.id %>" selected="selected"><%= selected_tag.text %></option>
              <%- end %>
            </select>
          </div>
        </div>
      <%- end %>
      
      <div class="float-right">
        <div class="float-left" style="padding-right: 5px; padding-left: 5px;"> 
          <select multiple="multiple" class="form-control" name='status-filter[]' id="status-filter" style="min-width: 300px; width: auto"  data-transition-cards-target="filter">
            <%- ['Actual', 'Planned', 'No Comment', 'Gap in Effort'].each do |option| %>
              <option value="<%= option %>" <%= 'selected' if option == 'Actual' %>><%= option %></option>
            <%- end %>
          </select>
        </div>
        
        <%- print_transition_card_path = if @selected_date 
              transition_card_path(@scorecard, format: :pdf, selected_date: @selected_date, key: SecureRandom.urlsafe_base64(5))
            else
              transition_card_path(@scorecard, format: :pdf, key: SecureRandom.urlsafe_base64(5))
            end
        %>
        <%= link_to(print_transition_card_path, class: 'btn btn-primary', data: { toggle: "tooltip"}, title: "Print") do
          content_tag(:i, '', class: "fa fa-print")
        end %>
        <%= link_to(show_shared_link_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Share") do
          content_tag(:i, '', class: "fa fa-share-alt")
        end %>
        <% if policy(:scorecard).copy_options? %>
          <%= link_to(copy_options_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Copy") do
            content_tag(:i, '', class: "fa fa-files-o")
          end %>
        <% end %>
        <% if policy(:scorecard).merge_options? %>
          <%= link_to(merge_options_transition_card_path(@scorecard), class: 'remote-link btn btn-primary', data: { toggle: "tooltip"}, title: "Merge") do
            content_tag(:i, '', class: "fa fa-file-text-o")
          end %>
        <% end %>
        
      </div>
    </div>
  </div>
  <div class="box-body scorecard-matrix pl-3" data-transition-cards-target="grid">
    <div class="outer">
      <div class="inner">
        <table class="pre-scrollable"> 
          <thead>
            <tr>
              <th>&nbsp;</th>
              <% @focus_areas.each_with_index do |focus_area, index| %>
                <th colspan="<%= focus_area.characteristics.count %>" class="legend">
                  <div data-toggle="tooltip" data-placement="top" title="<%= focus_area.name %>">
                    <span class="text-color<%="#{index+1}"%>">Focus Area <%= index + 1 %>
                    </span>
                  </div>
                </th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @results.each do |result| %>
            <tr>
              <th>
                <!--span data-toggle="tooltip" data-placement="top" title="<%= result.dig('initiative', 'name') %>"-->
                  <%= 
                    link_to(
                      result.dig('initiative', 'name'), 
                      initiative_path(id: result.dig('initiative', 'id')), 
                      class: 'truncate',
                      data: {
                        toggle: 'tooltip',
                        placement: 'top',
                        title: result.dig('initiative', 'name')
                      }
                    )
                  %>
                </span>
              </th>
              <% @characteristics.each do |characteristic| %>
                <td 
                  data-toggle="tooltip" 
                  data-placement="left" 
                  data-container=".inner" 
                  data-status="<%= result.dig(characteristic.id.to_s, 'status') %>"
                  title="<%= result.dig(characteristic.id.to_s, 'name') %>" 
                  class="<%= cell_class(result, @focus_areas, characteristic) %>">
                  <span>&nbsp;</span>
                </td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr class="chars"> 
              <td>
                &nbsp;
              </td>
              <% @characteristics.each do |characteristic| %>
                <td>
                  <span class="text-color<%= @focus_areas.index(characteristic.focus_area)+1%>"><%= characteristic.name %></span>
                </td>
              <% end %>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>